[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=DFC6442E4F5A22AE88E9C08A989302AD
ProjectName=Iris Relay Lab

[/Script/IrisDemo.IrisDemoGameMode]
; Set to True to enable Scenario A Iris role-based group filtering by default.
; Runtime option ScenarioAEnableRoleFiltering still overrides this value.
bScenarioAEnableRoleFiltering=True
